import Layout from '@/components/layout/Layout'
import { cn } from '@/utils/libs/utils'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import '@/styles/globals.css'

const fontSans = Inter(
  { 
    subsets: ['latin'],
  }
)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body 
      className={cn(
        "min-h-screen",
        fontSans.className
      )}      
      >
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}
