import '@/styles/globals.css'
import { cn } from '@/utils/libs/utils'
import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'

const fontSans = FontSans(
  { 
    subsets: ['latin'],
  }
)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body 
      className={cn(
        "min-h-screen",
        fontSans.className
      )}
      
      >{children}</body>
    </html>
  )
}
